# Generated by Django 5.2.1 on 2025-06-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_labsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsession',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.material'),
        ),
    ]
