# Generated by Django 5.2.1 on 2025-06-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_labsession_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='network_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labsession',
            name='target_container_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='target_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
