# Generated by Django 5.2.1 on 2025-06-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_labsession_network_id_labsession_target_container_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_steps', to='api.material')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('material', 'step_number')},
            },
        ),
    ]
