# Generated by Django 5.2.1 on 2025-06-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_guidestep_trigger_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidestep',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
